// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZn509Q_0Swj4HR31HkEbQJYmeqEs91Ow',
    appId: '1:516457410120:web:307739a286bc3de13cb27d',
    messagingSenderId: '516457410120',
    projectId: 'tickets-eff42',
    authDomain: 'tickets-eff42.firebaseapp.com',
    storageBucket: 'tickets-eff42.firebasestorage.app',
    measurementId: 'G-XVW1RSY8X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6k7ZPrG8au_tOeyES00Cp_Qpayqi9JvY',
    appId: '1:516457410120:android:c55ec4049e28fc6b3cb27d',
    messagingSenderId: '516457410120',
    projectId: 'tickets-eff42',
    storageBucket: 'tickets-eff42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDONYjzDStd1kHSVSMLruEugtVN5691OI',
    appId: '1:516457410120:ios:094f8aff23ae7ffb3cb27d',
    messagingSenderId: '516457410120',
    projectId: 'tickets-eff42',
    storageBucket: 'tickets-eff42.firebasestorage.app',
    iosBundleId: 'com.tuempresa.helpDeskApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDONYjzDStd1kHSVSMLruEugtVN5691OI',
    appId: '1:516457410120:ios:094f8aff23ae7ffb3cb27d',
    messagingSenderId: '516457410120',
    projectId: 'tickets-eff42',
    storageBucket: 'tickets-eff42.firebasestorage.app',
    iosBundleId: 'com.tuempresa.helpDeskApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZn509Q_0Swj4HR31HkEbQJYmeqEs91Ow',
    appId: '1:516457410120:web:b2a9cb97fceb39933cb27d',
    messagingSenderId: '516457410120',
    projectId: 'tickets-eff42',
    authDomain: 'tickets-eff42.firebaseapp.com',
    storageBucket: 'tickets-eff42.firebasestorage.app',
    measurementId: 'G-EX6PY92YKB',
  );
}
